finished workflow call for build-test-deploy

diff --git a/.github/workflows/build-test-deploy.yaml b/.github/workflows/build-test-deploy.yaml
--- a/.github/workflows/build-test-deploy.yaml
+++ b/.github/workflows/build-test-deploy.yaml
@@ -3,104 +3,33 @@
 #     `brew install act`
 #  2. Create a .secret file with the following content:
 #     `GITHUB_TOKEN=your_github_token`
-#  3. Create a pull_request.json file in case of a pull request with the following content:
-#     `{"pull_request": {"number": <PR number>, "head": {"ref": "<PR branch name>", "sha": "PR commit sha"}, "base": {"ref": "main"}}, "repository": {"name": "juno", "owner": {"login": "cloudoperators"}}}`
-#  4. Run the following command:
-# `act pull_request --container-architecture linux/amd64 -P default=catthehacker/ubuntu:act-latest  -j detect-changes -e act_pull_request.json`
+# WORKFLOW CALL
+# 1.Create a act_workflow_call.json file with the following content:
+#     `{"inputs": {"change": {"type": "package", "asset": "juno-ui-components"}, "node": "20.x"}}`
+# 2. Run the following command:
+#     `act workflow_call --eventpath act_workflow_call.json --container-architecture linux/amd64 -P default=catthehacker/ubuntu:act-latest -j test-package`
 
 name: Build, Test, and Deploy
 
 on:
-  pull_request:
-    types: [opened, synchronize, reopened]
-    paths:
-      - "apps/**"
-      - "libs/**"
+  workflow_call:
+    inputs:
+      change:
+        required: true
+        type: string
+      node:
+        required: true
+        type: string
 
 jobs:
-  detect-changes:
-    runs-on: [default]
-    outputs:
-      changes: ${{ steps.create-matrix-changes.outputs.changes}}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Generate app and lib filters
-        run: |
-          for folder in apps/*; do
-            folder_name=$(basename "$folder")
-            echo "$folder_name: $folder/**" >> temp_app_filters.yaml
-          done
-          for folder in libs/*; do
-            folder_name=$(basename "$folder")
-            echo "$folder_name: $folder/**" >> temp_lib_filters.yaml
-          done
-
-      - uses: dorny/paths-filter@v3
-        id: filters
-        with:
-          list-files: shell
-          filters: |
-            apps: apps/**
-            libs: libs/**
-
-      - uses: dorny/paths-filter@v3
-        id: app-filters
-        with:
-          list-files: shell
-          filters: temp_app_filters.yaml
-
-      - uses: dorny/paths-filter@v3
-        id: lib-filters
-        with:
-          list-files: shell
-          filters: temp_lib_filters.yaml
-
-      - name: Create changes array for the matrix strategy
-        id: create-matrix-changes
-        run: |
-          app_changes=$(echo '${{ steps.app-filters.outputs.changes }}' | jq -c '.[]')
-          lib_changes=$(echo '${{ steps.lib-filters.outputs.changes }}' | jq -c '.[]')
-
-          changes=()
-          for app in $app_changes; do
-            changes+=( "{\"type\":\"apps\",\"asset\":$app}" )
-          done
-          for change in $lib_changes; do
-            changes+=( "{\"type\":\"libs\",\"asset\":$change}" )
-          done
-          echo "changes=[$(IFS=,; echo "${changes[*]}")]" >> $GITHUB_OUTPUT
-
-      - name: Show outputs
-        run: |
-          echo "========"
-          cat temp_app_filters.yaml
-          echo "========"          
-          cat temp_lib_filters.yaml
-          echo "========"
-          echo apps: ${{ steps.filters.outputs.apps}}
-          echo apps_files: ${{ steps.filters.outputs.apps_files}}
-          echo app changes: ${{ steps.app-filters.outputs.changes}}          
-          echo libs: ${{ steps.filters.outputs.libs}}
-          echo libs_files: ${{ steps.filters.outputs.libs_files}}
-          echo lib changes: ${{ steps.lib-filters.outputs.changes}}
-          echo changes: ${{ toJson(steps.create-matrix-changes.outputs.changes) }}
-          echo "===================="
-
   check-3rd-party-licenses:
-    needs: detect-changes
     runs-on: [default]
-    strategy:
-      matrix:
-        change: ${{fromJson(needs.detect-changes.outputs.changes)}}
-        node: [20.x]
     steps:
       - name: Extract package name and type save them to env
         id: extract-attributes
         run: |
-          changed_package_type=$( echo '${{ toJson(matrix.change) }}' | jq -r '.type' )
-          changed_package=$( echo '${{ toJson(matrix.change) }}' | jq -r '.asset' )
+          changed_package_type=$( echo '${{ toJson(inputs.change) }}' | jq -r '.type' )
+          changed_package=$( echo '${{ toJson(inputs.change) }}' | jq -r '.asset' )
           echo "CHANGED_PACKAGE_TYPE=$changed_package_type" >> $GITHUB_ENV
           echo "CHANGED_PACKAGE=$changed_package" >> $GITHUB_ENV
 
@@ -110,10 +39,9 @@ jobs:
       - name: Setup node
         uses: actions/setup-node@v4
         with:
-          node-version: ${{ matrix.node }}
+          node-version: ${{ inputs.node }}
 
       - name: Remove all dependencies to our self hosted registry (temporary do tue not access from the internet)
-        if: ${{ !env.ACT }}
         run: |
           echo type: $CHANGED_PACKAGE_TYPE, package: $CHANGED_PACKAGE
           cd "$CHANGED_PACKAGE_TYPE/$CHANGED_PACKAGE"
@@ -125,7 +53,6 @@ jobs:
               .peerDependencies = $peerDeps' package.json > temp.json && mv temp.json package.json
 
       - name: Install npm dependencies and check 3rd party licenses
-        if: ${{ !env.ACT }}
         run: |
           echo type: $CHANGED_PACKAGE_TYPE, package: $CHANGED_PACKAGE
           cd "$CHANGED_PACKAGE_TYPE/$CHANGED_PACKAGE"
@@ -136,34 +63,55 @@ jobs:
           npm install -g license-checker-rseidelsohn
           license-checker-rseidelsohn -onlyAllow "MIT;ISC;Apache-2.0;BSD-2-Clause;BSD-3-Clause;BSD-4-Clause;CC-BY-3.0;CC-BY-4.0;BlueOak-1.0.0;CC0-1.0;0BSD;Python-2.0;BSD*;Unlicense"
 
-  test:
-    needs: [check-3rd-party-licenses, detect-changes]
+  test-package:
+    needs: [check-3rd-party-licenses]
     runs-on: [default]
-    strategy:
-      matrix:
-        change: ${{fromJson(needs.detect-changes.outputs.changes)}}
-        node: [20.x]
     steps:
       - name: Extract package name and type save them to env
         id: extract-attributes
         run: |
-          changed_package_type=$( echo '${{ toJson(matrix.change) }}' | jq -r '.type' )
-          changed_package=$( echo '${{ toJson(matrix.change) }}' | jq -r '.asset' )
+          changed_package_type=$( echo '${{ toJson(inputs.change) }}' | jq -r '.type' )
+          changed_package=$( echo '${{ toJson(inputs.change) }}' | jq -r '.asset' )
           echo "CHANGED_PACKAGE_TYPE=$changed_package_type" >> $GITHUB_ENV
           echo "CHANGED_PACKAGE=$changed_package" >> $GITHUB_ENV
 
-      # - name: Checkout
-      #   uses: actions/checkout@v4
+      - name: Skip if package contains dependencies to our self hosted registry (temporary do tue not access from the internet)
+        id: skip-check
+        run: |
+          skip_items=("juno-ui-components" "messages-provider" "url-state-router")
 
-      # - name: Setup node
-      #   uses: actions/setup-node@v4
-      #   with:
-      #     node-version: "20.x"
+          for item in "${skip_items[@]}"; do
+            if [[ "$CHANGED_PACKAGE" == *"$item"* ]]; then
+              echo "SKIP=true" >> $GITHUB_ENV
+              break
+            else
+              echo "SKIP=false" >> $GITHUB_ENV
+            fi
+          done
+
+      - name: Checkout
+        if: env.SKIP == 'false'
+        uses: actions/checkout@v4
+
+      - name: Setup node
+        if: env.SKIP == 'false'
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20.x"
 
       - name: Run tests
+        if: env.SKIP == 'false'
         run: |
-          echo "=======Running tests======="
-          echo "Change: ${{ toJson(matrix.change) }}"
-          echo "Node: ${{ toJson(matrix.node) }}"
           echo type: $CHANGED_PACKAGE_TYPE, package: $CHANGED_PACKAGE
-          echo "===================="
+          cd "$CHANGED_PACKAGE_TYPE/$CHANGED_PACKAGE"
+          npm i
+          npm run test
+
+      - name: Skip message
+        if: env.SKIP == 'true'
+        run: |
+          echo "==="
+          echo "Skipping job for $CHANGED_PACKAGE_TYPE/$CHANGED_PACKAGE as it contains self hosted registry (temporary do tue not access from the internet)"
+          echo "==="
+          # fail job when skippped so it do not trigger next job
+          exit 1
